name: Release

on:
  workflow_run:
    workflows:
      - Bump Version # Matches the name of the workflow to listen to
    types:
      - completed # Trigger only when the workflow finishes successfully

jobs:
  build-and-test:
    uses: ./.github/workflows/test-build.yml
    with:
      release: true
  release:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # Download the packaged artifact
      - name: Download Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-package

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      # Publish to npm
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish ./*.tgz

      - name: Set Version
        run: echo "RELEASE_VERSION=$(npm pkg get version)" >> $GITHUB_ENV
      # Create a GitHub release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ env.RELEASE_VERSION }}"
          release_name: Release ${{ env.RELEASE_VERSION }}
          body: |
            This release was automatically built and published using GitHub Actions.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

